apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mediawiki
  namespace: mediawiki
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mediawiki-srv
            port:
              number: {{ .Values.ingress.port }}
